name: uk_power
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.1.2+8

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.3.1
  http: ^0.13.4
  google_fonts: ^2.3.1
  intl: ^0.17.0
  faker: ^2.0.0
  dio: ^4.0.4
  logger: ^1.1.0
  path_provider: ^2.0.9
  url_launcher: ^6.0.20
  awesome_dialog: ^2.1.2
  tutorial_coach_mark: ^1.2.1
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/app_icons/app_icon.png"
  image_path_android: "assets/app_icons/app_icon.png"
  adaptive_icon_background: "assets/app_icons/background.png"
  adaptive_icon_foreground: "assets/app_icons/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icons/
